/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilancoba2;

import tampilancoba2.ConnectionDB;
import tampilancoba2.OptionMenu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author My MSI
 */
public class InputForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        kendaraanTxt = new javax.swing.JTextField();
        merkTxt = new javax.swing.JTextField();
        tujuanTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kecepatanTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        waktuTxt = new javax.swing.JTextField();
        prosesBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jarakTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stjbox = new javax.swing.JCheckBox();

        setTitle("DATA KENDARAAN");

        jLabel1.setText("Nama Pemilik");

        jLabel2.setText("Nama Kendaraan");

        jLabel3.setText("Merk/Brand Kendaraan");

        jLabel4.setText("Tujuan");

        jLabel5.setText("Kecepatan");

        jLabel6.setText("Waktu");

        prosesBtn.setText("Proses");
        prosesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBtnActionPerformed(evt);
            }
        });

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        hapusBtn.setText("Hapus");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Jarak");

        jarakTxt.setEditable(false);

        jLabel8.setText("KM");

        jLabel9.setText("JAM");

        jLabel10.setText("KM/JAM");

        stjbox.setText("Setuju");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prosesBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(simpanBtn)
                        .addGap(40, 40, 40)
                        .addComponent(hapusBtn))
                    .addComponent(namaTxt)
                    .addComponent(kendaraanTxt)
                    .addComponent(merkTxt)
                    .addComponent(tujuanTxt)
                    .addComponent(kecepatanTxt)
                    .addComponent(waktuTxt)
                    .addComponent(jarakTxt))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stjbox)
                            .addComponent(jLabel10))
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(kendaraanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(merkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tujuanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stjbox)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kecepatanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(waktuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jarakTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesBtn)
                    .addComponent(simpanBtn)
                    .addComponent(hapusBtn))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        namaTxt.setText("");
        kendaraanTxt.setText("");
        merkTxt.setText("");
        tujuanTxt.setText("");
        kecepatanTxt.setText("");
        waktuTxt.setText("");
        jarakTxt.setText("");
        stjbox.setSelected(false);
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void prosesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBtnActionPerformed

        if (kecepatanTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Periksa Data yang anda input");
        } else if (waktuTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Periksa Data yang anda input");
        }else{
            double kecepatan = Double.valueOf(kecepatanTxt.getText().trim());
            double waktu = Double.valueOf(waktuTxt.getText().trim());
        
            double hasil = kecepatan*waktu;
            jarakTxt.setText(""+hasil);
            
        }
    }//GEN-LAST:event_prosesBtnActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        if(stjbox.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Klick Centang untuk simpan ","Error",JOptionPane.ERROR_MESSAGE);
        }else if(kecepatanTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Periksa Data yang anda input");
        } else if (waktuTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Periksa Data yang anda input");
        }else{
            double kecepatan = Double.valueOf(kecepatanTxt.getText().trim());
            double waktu = Double.valueOf(waktuTxt.getText().trim());
        
            double hasil = kecepatan*waktu;
            jarakTxt.setText(""+hasil);
            
        }
        try {
            String sql = "Insert Into Kendaraan(Nama_Pemilik,Nama_Kendaraan,Nama_Merk,Tujuan,kecepatan,waktu,jarak) VALUES ('"
                    
                    +namaTxt.getText()+"','"
                    +kendaraanTxt.getText()+"','"
                    +merkTxt.getText()+"','"
                    +tujuanTxt.getText()+"','"
                    +kecepatanTxt.getText()+"','"
                    +waktuTxt.getText()+"','"
                    +jarakTxt.getText()+"')";
            Connection conn = (Connection)ConnectionDB.connectDatabase();
            PreparedStatement pst = (PreparedStatement)conn.prepareStatement(sql);
            pst.execute();
                    } catch (SQLException ex) {
            Logger.getLogger(InputForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        OptionMenu optionMenu = new OptionMenu();
        optionMenu.setVisible(true);
        this.getDesktopPane().add(optionMenu);
        this.dispose();
    }//GEN-LAST:event_simpanBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jarakTxt;
    private javax.swing.JTextField kecepatanTxt;
    private javax.swing.JTextField kendaraanTxt;
    private javax.swing.JTextField merkTxt;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JButton prosesBtn;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JCheckBox stjbox;
    private javax.swing.JTextField tujuanTxt;
    private javax.swing.JTextField waktuTxt;
    // End of variables declaration//GEN-END:variables
}
